# Generated by Django 2.1.5 on 2019-02-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aks',
            name='img',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
    ]
