# Generated by Django 2.1.5 on 2019-02-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edit', '0002_auto_20190211_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='aks',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
